version: 0.2

phases:
  build:
    commands:
      - dotnet restore
      - dotnet publish -c Release
      - cd bin/Release/netcoreapp1.0/publish
      - zip ../../../../MyProject.zip *
      - cd ../../../..
      - aws lambda update-function-code 
        --function-name myLambdaFunctionMax 
        --zip-file fileb://MyProject.zip

        #aws lambda update-function-code --function-name myLambdaFunctionMax --zip-file fileb://MyProject.zip 
